# Generated by Django 5.1.2 on 2024-10-18 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_id', models.CharField(max_length=100)),
                ('annotation', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabsl_internal_option_id', models.IntegerField(blank=True, null=True)),
                ('option_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CognitionRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('representation_name', models.CharField(max_length=40)),
                ('representation_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(blank=True, max_length=100, null=True)),
                ('team2', models.CharField(blank=True, max_length=100, null=True)),
                ('half', models.CharField(blank=True, max_length=100, null=True)),
                ('is_testgame', models.BooleanField(blank=True, null=True)),
                ('head_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('assistent_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('RAW', 'raw'), ('JPEG', 'jpeg')], max_length=10, null=True)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('blurredness_value', models.IntegerField(blank=True, null=True)),
                ('brightness_value', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_version', models.CharField(blank=True, max_length=5, null=True)),
                ('player_number', models.IntegerField(blank=True, null=True)),
                ('head_number', models.IntegerField(blank=True, null=True)),
                ('body_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('head_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('representation_list', models.JSONField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, max_length=200, null=True)),
                ('combined_log_path', models.CharField(blank=True, max_length=200, null=True)),
                ('sensor_log_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BallModel', models.IntegerField(blank=True, null=True)),
                ('CameraMatrix', models.IntegerField(blank=True, null=True)),
                ('CameraMatrixTop', models.IntegerField(blank=True, null=True)),
                ('FieldPercept', models.IntegerField(blank=True, null=True)),
                ('FieldPerceptTop', models.IntegerField(blank=True, null=True)),
                ('GoalPercept', models.IntegerField(blank=True, null=True)),
                ('GoalPerceptTop', models.IntegerField(blank=True, null=True)),
                ('RansacLinePercept', models.IntegerField(blank=True, null=True)),
                ('RansacCirclePercept2018', models.IntegerField(blank=True, null=True)),
                ('ShortLinePercept', models.IntegerField(blank=True, null=True)),
                ('ScanLineEdgelPercept', models.IntegerField(blank=True, null=True)),
                ('ScanLineEdgelPerceptTop', models.IntegerField(blank=True, null=True)),
                ('OdometryData', models.IntegerField(blank=True, null=True)),
                ('num_cognition_frames', models.IntegerField(blank=True, null=True)),
                ('num_motion_frames', models.IntegerField(blank=True, null=True)),
                ('num_jpg_bottom', models.IntegerField(blank=True, null=True)),
                ('num_jpg_top', models.IntegerField(blank=True, null=True)),
                ('num_bottom', models.IntegerField(blank=True, null=True)),
                ('num_top', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotionRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_frame_number', models.IntegerField(blank=True, null=True)),
                ('sensor_frame_time', models.IntegerField(blank=True, null=True)),
                ('representation_name', models.CharField(blank=True, max_length=40, null=True)),
                ('representation_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XabslSymbolComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XabslSymbolSparse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorOptionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabsl_internal_state_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('target', models.BooleanField(blank=True, null=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options_states', to='api.behavioroption')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorFrameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='api.behavioroption')),
                ('active_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='api.behavioroptionstate')),
            ],
        ),
    ]
