# Generated by Django 5.0.6 on 2024-08-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrameTime',
        ),
    ]
