# Generated by Django 5.0.6 on 2024-08-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robotdata',
            unique_together={('game', 'player_number', 'head_number', 'log_path')},
        ),
    ]
