# Generated by Django 5.1.2 on 2024-10-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('log', 'camera', 'type', 'frame_number')},
        ),
    ]
