# Generated by Django 5.0.6 on 2024-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_robotdata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robotdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='annotation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
