# Generated by Django 5.0.6 on 2024-08-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_robotdata_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageannotation',
            old_name='type',
            new_name='annotation_id',
        ),
    ]
