# Generated by Django 5.0.6 on 2024-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cameramatrix_image_imageannotation_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='representations',
            field=models.JSONField(default={}),
        ),
    ]
