# Generated by Django 5.1.2 on 2024-10-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_xabslsymbolcomplete_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motionrepresentation',
            unique_together={('log_id', 'sensor_frame_number', 'representation_name')},
        ),
        migrations.AddIndex(
            model_name='motionrepresentation',
            index=models.Index(fields=['log_id', 'sensor_frame_number'], name='api_motionr_log_id__bc12e3_idx'),
        ),
    ]
