# Generated by Django 5.0.6 on 2024-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_event_time_event_end_day_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
