# Generated by Django 5.1.2 on 2024-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_motionrepresentation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatus',
            name='AccelerometerData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='ButtonData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='FSRData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='GyrometerData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='IMUData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='InertialSensorData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='MotionStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='MotorJointData',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='SensorJointData',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
