# Generated by Django 5.0.6 on 2024-07-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_log_representations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='representations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
