# Generated by Django 5.0.6 on 2024-09-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_end_day_alter_event_start_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotdata',
            old_name='representations',
            new_name='representation_list',
        ),
        migrations.CreateModel(
            name='Representations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('robotdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='api.robotdata')),
            ],
        ),
    ]
