# Generated by Django 5.1.2 on 2024-11-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logstatus_accelerometerdata_logstatus_buttondata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatus',
            name='BallCandidates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logstatus',
            name='BallCandidatesTop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
