# Generated by Django 5.0.6 on 2024-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_log_representations'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='head_serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='robot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='player_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
