# Generated by Django 5.0.6 on 2024-07-28 11:01

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_image_camera_log_head_serial_log_robot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='frame_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cameramatrix',
            name='frame_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(blank=True, choices=[('RAW', 'raw'), ('JPEG', 'jpeg')], max_length=10, null=True),
        ),
    ]
