# Generated by Django 5.1.2 on 2024-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_annotation_annotation_id_remove_annotation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatus',
            name='FrameInfo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
