# Generated by Django 5.0.6 on 2024-09-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cognitionrepresentation_delete_representations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_frame_number', models.IntegerField(blank=True, null=True)),
                ('sensor_frame_time', models.IntegerField(blank=True, null=True)),
                ('representation_name', models.CharField(blank=True, max_length=40, null=True)),
                ('representation_data', models.JSONField(blank=True, null=True)),
                ('robotdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_repr', to='api.robotdata')),
            ],
        ),
        migrations.DeleteModel(
            name='SensorLog',
        ),
    ]
