# Generated by Django 5.0.6 on 2024-08-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_comment_event_country_event_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('frame_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
