# Generated by Django 5.1.2 on 2025-02-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_logstatus_frameinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logstatus',
            options={'verbose_name_plural': 'Log status'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='log',
            new_name='log_id',
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('log_id', 'camera', 'type', 'frame_number')},
        ),
    ]
