# Generated by Django 5.0.6 on 2024-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sensorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorlog',
            old_name='frame_number',
            new_name='sensor_frame_number',
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='sensor_frame_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
