# Generated by Django 5.0.6 on 2024-09-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_logs_alter_cognitionrepresentation_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='game',
            new_name='game_id',
        ),
    ]
