# Generated by Django 5.1.2 on 2025-02-09 19:33

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def migrate_game_to_generic(apps, schema_editor):
    Log = apps.get_model('api', 'Log')
    Game = apps.get_model('api', 'Game')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get the ContentType for the Game model
    game_content_type = ContentType.objects.get_for_model(Game)

    # Migrate logs
    for log in Log.objects.all():
        if log.game_id:
            log.content_type = game_content_type
            log.object_id = log.game_id.id
            log.save()


def reverse_migrate_game_to_generic(apps, schema_editor):
    Log = apps.get_model('api', 'Log')
    Game = apps.get_model('api', 'Game')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get the ContentType for the Game model
    game_content_type = ContentType.objects.get_for_model(Game)

    # Reverse migration
    for log in Log.objects.filter(content_type=game_content_type):
        log.game_id = Game.objects.get(id=log.object_id)
        log.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_log_content_type_log_object_id_experiment'),
    ]

    operations = [
        migrations.RunPython(migrate_game_to_generic, reverse_migrate_game_to_generic),
    ]
