# Generated by Django 5.0.6 on 2024-09-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_game_logs_game_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
