# Generated by Django 5.0.6 on 2024-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_logs_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='event',
            new_name='event_id',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('event_id', 'start_time', 'half')},
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
