# Generated by Django 5.0.6 on 2024-09-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_event_game_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motionrepresentation',
            old_name='robotdata',
            new_name='log_id',
        ),
    ]
