# Generated by Django 5.1.2 on 2025-02-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_log_content_type_alter_log_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='game_id',
        ),
    ]
