# Generated by Django 5.0.6 on 2024-09-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_robotdata_motionrepresentation_log_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cognitionrepresentation',
            old_name='log',
            new_name='log_id',
        ),
        migrations.RenameField(
            model_name='cognitionrepresentation',
            old_name='data',
            new_name='representation_data',
        ),
        migrations.RenameField(
            model_name='cognitionrepresentation',
            old_name='name',
            new_name='representation_name',
        ),
        migrations.AlterUniqueTogether(
            name='cognitionrepresentation',
            unique_together={('log_id', 'frame_number', 'representation_name')},
        ),
        migrations.AlterUniqueTogether(
            name='motionrepresentation',
            unique_together={('log_id', 'sensor_frame_number', 'representation_name')},
        ),
    ]
