# Generated by Django 5.0.6 on 2024-08-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_game_assistent_ref_game_comment_game_field_game_half_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
    ]
