# Generated by Django 5.0.6 on 2024-08-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_game_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('event', 'start_time', 'half')},
        ),
    ]
