# Generated by Django 5.0.6 on 2024-09-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_log_cognitionrepresentation_log_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motionrepresentation',
            unique_together=set(),
        ),
    ]
