# Generated by Django 5.0.6 on 2024-08-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_game_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(blank=True, null=True)),
                ('robot_number', models.IntegerField(blank=True, null=True)),
                ('body_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('head_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('representations', models.JSONField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_data', to='api.game')),
            ],
        ),
        migrations.AlterField(
            model_name='cameramatrix',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_matrix', to='api.robotdata'),
        ),
        migrations.AlterField(
            model_name='image',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.robotdata'),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
