# Generated by Django 5.0.6 on 2024-09-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_motionrepresentation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cognitionrepresentation',
            unique_together=set(),
        ),
    ]
