# Generated by Django 5.0.6 on 2024-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_robotdata_alter_cameramatrix_log_alter_image_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotdata',
            name='robot_version',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
