# Generated by Django 5.1.2 on 2025-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_url_videorecording_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
