# Generated by Django 5.0.6 on 2024-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_cognitionrepresentation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='log',
            name='num_cognition_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='num_motion_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
