# Generated by Django 5.0.6 on 2024-08-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_robotdata_robot_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotdata',
            old_name='robot_number',
            new_name='head_number',
        ),
    ]
