# Generated by Django 5.0.6 on 2024-09-29 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_game_unique_together_log_num_cognition_frames_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabsl_internal_option_id', models.IntegerField(blank=True, null=True)),
                ('option_name', models.CharField(blank=True, max_length=40, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options', to='api.log')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorOptionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabsl_internal_state_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('target', models.BooleanField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options_states', to='api.log')),
                ('options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options_states', to='api.behavioroption')),
            ],
        ),
    ]
