# Generated by Django 5.0.6 on 2024-08-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_robot_number_robotdata_head_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robotdata',
            unique_together={('game', 'player_number', 'head_number')},
        ),
    ]
