# Generated by Django 5.0.6 on 2024-09-29 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_options_id_behavioroptionstate_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorFrameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('time_of_execution', models.IntegerField(blank=True, null=True)),
                ('state_time', models.IntegerField(blank=True, null=True)),
                ('active_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='api.behavioroptionstate')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='api.log')),
                ('options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='api.behavioroption')),
            ],
        ),
    ]
