# Generated by Django 5.0.6 on 2024-08-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_robotdata_log_path_robotdata_sensor_log_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorLog',
        ),
    ]
