# Generated by Django 5.0.6 on 2024-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_behaviorframeoption'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
