# Generated by Django 5.1.2 on 2025-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_log_content_type_remove_log_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitionframe',
            name='frame_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionframe',
            name='frame_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
