# Generated by Django 5.0.6 on 2024-08-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_sensorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_frame_number', models.IntegerField(blank=True, null=True)),
                ('sensor_frame_time', models.IntegerField(blank=True, null=True)),
                ('representation_name', models.CharField(blank=True, max_length=40, null=True)),
                ('representation_data', models.JSONField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorlogs', to='api.robotdata')),
            ],
        ),
    ]
