# Generated by Django 5.0.6 on 2024-10-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_image_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='blurredness_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='brightness_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
