# Generated by Django 5.0.6 on 2024-08-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sensorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorlog',
            old_name='log',
            new_name='robotdata',
        ),
    ]
