# Generated by Django 5.0.6 on 2024-08-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_log_sensorlog_robotdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('log', 'camera', 'type', 'frame_number')},
        ),
        migrations.DeleteModel(
            name='CameraMatrix',
        ),
    ]
