# Generated by Django 5.1.2 on 2025-02-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_cognitionframe_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cognitionframe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cognitionframe',
            name='log_id',
        ),
        migrations.AlterUniqueTogether(
            name='motionframe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='motionframe',
            name='log_id',
        ),
    ]
