# Generated by Django 5.0.6 on 2024-10-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_log_combined_log_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='XabslSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('symbol_type', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol_name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol_value', models.CharField(blank=True, max_length=40, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabsl_symbols', to='api.log')),
            ],
        ),
    ]
