# Generated by Django 5.1.2 on 2025-02-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_cognitionframe_unique_together_and_more'),
        ('cognition', '0002_cognitionframe_alter_ballcandidates_frame_and_more'),
        ('motion', '0002_motionframe_alter_accelerometerdata_frame_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CognitionFrame',
        ),
        migrations.DeleteModel(
            name='MotionFrame',
        ),
    ]
