# Generated by Django 5.0.6 on 2024-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_xabslsymbol2_alter_xabslsymbol_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabslsymbol',
            name='symbol_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
