# Generated by Django 5.0.6 on 2024-10-06 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_xabslsymbol_symbol_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabslsymbol',
            name='symbol_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
