# Generated by Django 5.1.2 on 2025-02-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='framefilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_filter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalpercept', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='goalpercepttop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalpercepttop', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='multiballpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiballpercept', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='odometrydata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometrydata', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='ransaccirclepercept2018',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ransaccirclepercept2018', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='ransaclinepercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ransaclinepercept', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='scanlineedgelpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlineedgelpercept', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='scanlineedgelpercepttop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlineedgelpercepttop', to='cognition.cognitionframe'),
        ),
        migrations.AddField(
            model_name='shortlinepercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlinepercept', to='cognition.cognitionframe'),
        ),
        migrations.AddIndex(
            model_name='cognitionframe',
            index=models.Index(fields=['log_id', 'frame_number'], name='cognition_c_log_id__625273_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cognitionframe',
            unique_together={('log_id', 'frame_number')},
        ),
        migrations.AddConstraint(
            model_name='cameramatrixtop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_cameramatrixtop'),
        ),
        migrations.AddConstraint(
            model_name='cameramatrix',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_cameramatrix'),
        ),
        migrations.AddConstraint(
            model_name='ballmodel',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ballmodel'),
        ),
        migrations.AddConstraint(
            model_name='ballcandidatestop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ballcandidatestop'),
        ),
        migrations.AddConstraint(
            model_name='ballcandidates',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ballcandidates'),
        ),
        migrations.AddConstraint(
            model_name='fieldpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_fieldpercept'),
        ),
        migrations.AddConstraint(
            model_name='fieldpercepttop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_fieldpercepttop'),
        ),
        migrations.AddConstraint(
            model_name='goalpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_goalpercept'),
        ),
        migrations.AddConstraint(
            model_name='goalpercepttop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_goalpercepttop'),
        ),
        migrations.AddConstraint(
            model_name='multiballpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_multiballpercept'),
        ),
        migrations.AddConstraint(
            model_name='odometrydata',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_odometrydata'),
        ),
        migrations.AddConstraint(
            model_name='ransaccirclepercept2018',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ransaccirclepercept2018'),
        ),
        migrations.AddConstraint(
            model_name='ransaclinepercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ransaclinepercept'),
        ),
        migrations.AddConstraint(
            model_name='scanlineedgelpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_scanlineedgelpercept'),
        ),
        migrations.AddConstraint(
            model_name='scanlineedgelpercepttop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_scanlineedgelpercepttop'),
        ),
        migrations.AddConstraint(
            model_name='shortlinepercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_shortlinepercept'),
        ),
    ]
