# Generated by Django 5.1.2 on 2025-02-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_cognitionframe_unique_together_and_more'),
        ('cognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitionFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('frame_time', models.IntegerField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitionframe', to='api.log')),
            ],
        ),
        migrations.AlterField(
            model_name='ballcandidates',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballcandidates', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='ballcandidatestop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballcandidatestop', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='ballmodel',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballmodel', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='cameramatrix',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameramatrix', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='cameramatrixtop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameramatrixtop', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='fieldpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldpercept', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='fieldpercepttop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldpercepttop', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='goalpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalpercept', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='goalpercepttop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalpercepttop', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='multiballpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiballpercept', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='odometrydata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometrydata', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='ransaccirclepercept2018',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ransaccirclepercept2018', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='ransaclinepercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ransaclinepercept', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='scanlineedgelpercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlineedgelpercept', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='scanlineedgelpercepttop',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlineedgelpercepttop', to='cognition.cognitionframe'),
        ),
        migrations.AlterField(
            model_name='shortlinepercept',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlinepercept', to='cognition.cognitionframe'),
        ),
        migrations.AddIndex(
            model_name='cognitionframe',
            index=models.Index(fields=['log_id', 'frame_number'], name='cognition_c_log_id__625273_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cognitionframe',
            unique_together={('log_id', 'frame_number')},
        ),
    ]
