# Generated by Django 5.1.2 on 2025-02-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognition', '0002_cognitionframe_alter_ballcandidates_frame_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballcandidates',
            options={'verbose_name_plural': 'Ball Candidates'},
        ),
        migrations.AlterModelOptions(
            name='ballcandidatestop',
            options={'verbose_name_plural': 'Ball Candidates Top'},
        ),
        migrations.AlterModelOptions(
            name='ballmodel',
            options={'verbose_name_plural': 'Ball Model'},
        ),
        migrations.AlterModelOptions(
            name='cameramatrix',
            options={'verbose_name_plural': 'Camera Matrix'},
        ),
        migrations.AlterModelOptions(
            name='cameramatrixtop',
            options={'verbose_name_plural': 'Camera Matrix Top'},
        ),
        migrations.AlterModelOptions(
            name='cognitionframe',
            options={'verbose_name_plural': 'Cognition Frames'},
        ),
        migrations.AlterModelOptions(
            name='fieldpercept',
            options={'verbose_name_plural': 'Field Percept'},
        ),
        migrations.AlterModelOptions(
            name='fieldpercepttop',
            options={'verbose_name_plural': 'Field Percept Top'},
        ),
        migrations.AlterModelOptions(
            name='goalpercept',
            options={'verbose_name_plural': 'Goal Percept'},
        ),
        migrations.AlterModelOptions(
            name='goalpercepttop',
            options={'verbose_name_plural': 'Goal Percept Top'},
        ),
        migrations.AlterModelOptions(
            name='multiballpercept',
            options={'verbose_name_plural': 'Multi Ball Percept'},
        ),
        migrations.AlterModelOptions(
            name='odometrydata',
            options={'verbose_name_plural': 'Odometry Data'},
        ),
        migrations.AlterModelOptions(
            name='ransaccirclepercept2018',
            options={'verbose_name_plural': 'Ransac Circle Percept 2018'},
        ),
        migrations.AlterModelOptions(
            name='ransaclinepercept',
            options={'verbose_name_plural': 'Ransac Line Percept'},
        ),
        migrations.AlterModelOptions(
            name='scanlineedgelpercept',
            options={'verbose_name_plural': 'Scanline Edgel Percept'},
        ),
        migrations.AlterModelOptions(
            name='scanlineedgelpercepttop',
            options={'verbose_name_plural': 'Scanline Edgel Percept Top'},
        ),
        migrations.AlterModelOptions(
            name='shortlinepercept',
            options={'verbose_name_plural': 'Short Line Percept'},
        ),
        migrations.AddConstraint(
            model_name='ballcandidates',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ballcandidates'),
        ),
        migrations.AddConstraint(
            model_name='ballcandidatestop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ballcandidatestop'),
        ),
        migrations.AddConstraint(
            model_name='ballmodel',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ballmodel'),
        ),
        migrations.AddConstraint(
            model_name='cameramatrix',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_cameramatrix'),
        ),
        migrations.AddConstraint(
            model_name='cameramatrixtop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_cameramatrixtop'),
        ),
        migrations.AddConstraint(
            model_name='fieldpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_fieldpercept'),
        ),
        migrations.AddConstraint(
            model_name='fieldpercepttop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_fieldpercepttop'),
        ),
        migrations.AddConstraint(
            model_name='goalpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_goalpercept'),
        ),
        migrations.AddConstraint(
            model_name='goalpercepttop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_goalpercepttop'),
        ),
        migrations.AddConstraint(
            model_name='multiballpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_multiballpercept'),
        ),
        migrations.AddConstraint(
            model_name='odometrydata',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_odometrydata'),
        ),
        migrations.AddConstraint(
            model_name='ransaccirclepercept2018',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ransaccirclepercept2018'),
        ),
        migrations.AddConstraint(
            model_name='ransaclinepercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_ransaclinepercept'),
        ),
        migrations.AddConstraint(
            model_name='scanlineedgelpercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_scanlineedgelpercept'),
        ),
        migrations.AddConstraint(
            model_name='scanlineedgelpercepttop',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_scanlineedgelpercepttop'),
        ),
        migrations.AddConstraint(
            model_name='shortlinepercept',
            constraint=models.UniqueConstraint(fields=('frame',), name='unique_frame_id_shortlinepercept'),
        ),
    ]
