# Generated by Django 5.1.2 on 2024-12-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vatuser',
            name='token',
        ),
    ]
