# Generated by Django 5.0.6 on 2024-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
