# Generated by Django 5.0.6 on 2024-08-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_vat_user_orga'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vat_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='vat_user',
            name='orga',
        ),
        migrations.AddField(
            model_name='vat_user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='user.organization'),
        ),
    ]
