# Generated by Django 5.0.6 on 2024-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_vatuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatuser',
            name='first_name',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vatuser',
            name='last_name',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
