# Generated by Django 5.1.2 on 2025-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_vatuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vatuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
