apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vat-backend
  template:
    metadata:
      labels:
        app: vat-backend
    spec:
      initContainers:
      - name: django-migrations
        image: ghcr.io/berlinunited/django_backend:latest
        command: 
        - /bin/sh
        - -c
        - |
          python manage.py migrate
        env:
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: "vat"
        - name: VAT_POSTGRES_USER
          value: "naoth"
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: "postgres-postgresql.postgres.svc.cluster.local"
        - name: VAT_POSTGRES_PORT
          value: "5432"
      containers:
      - name: backend
        image: ghcr.io/berlinunited/django_backend:latest
        env:
        - name: USE_POSTGRES
          value: "true"
        - name: VAT_POSTGRES_DB
          value: "vat"
        - name: VAT_POSTGRES_USER
          value: "naoth"
        - name: VAT_POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: "password"
        - name: VAT_POSTGRES_HOST
          value: "postgres-postgresql.postgres.svc.cluster.local"
        - name: VAT_POSTGRES_PORT
          value: "5432"
        - name: VAT_BACKUP_FOLDER
          value: "/backup"
        volumeMounts:
        - mountPath: /backup
          name: backupmount
      imagePullSecrets:
      - name: github-access
      volumes:
      - name: backupmount
        hostPath:
          path: /opt/backup # path to a folder on the actual node