# Generated by Django 5.1.2 on 2025-02-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_cognitionframe_unique_together_and_more'),
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('frame_time', models.IntegerField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motionframe', to='api.log')),
            ],
        ),
        migrations.AlterField(
            model_name='accelerometerdata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accelerometerdata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='buttondata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttondata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='fsrdata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrdata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='gyrometerdata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyrometerdata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='imudata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imudata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='inertialsensordata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inertialsensordata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='motionstatus',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motionstatus', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='motorjointdata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorjointdata', to='motion.motionframe'),
        ),
        migrations.AlterField(
            model_name='sensorjointdata',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorjointdata', to='motion.motionframe'),
        ),
        migrations.AddIndex(
            model_name='motionframe',
            index=models.Index(fields=['log_id', 'frame_number'], name='motion_moti_log_id__bd9f58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motionframe',
            unique_together={('log_id', 'frame_number')},
        ),
    ]
