# Generated by Django 5.1.2 on 2025-02-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motion', '0002_motionframe_alter_accelerometerdata_frame_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accelerometerdata',
            options={'verbose_name_plural': 'Accelerometer Data'},
        ),
        migrations.AlterModelOptions(
            name='buttondata',
            options={'verbose_name_plural': 'Button Data'},
        ),
        migrations.AlterModelOptions(
            name='fsrdata',
            options={'verbose_name_plural': 'FSR Data'},
        ),
        migrations.AlterModelOptions(
            name='gyrometerdata',
            options={'verbose_name_plural': 'Gyrometer Data'},
        ),
        migrations.AlterModelOptions(
            name='imudata',
            options={'verbose_name_plural': 'IMU Data'},
        ),
        migrations.AlterModelOptions(
            name='inertialsensordata',
            options={'verbose_name_plural': 'Inertial Sensor Data'},
        ),
        migrations.AlterModelOptions(
            name='motionframe',
            options={'verbose_name_plural': 'Motion Frames'},
        ),
        migrations.AlterModelOptions(
            name='motionstatus',
            options={'verbose_name_plural': 'Motion Status'},
        ),
        migrations.AlterModelOptions(
            name='motorjointdata',
            options={'verbose_name_plural': 'Motor Joint Data'},
        ),
        migrations.AlterModelOptions(
            name='sensorjointdata',
            options={'verbose_name_plural': 'Sensor Joint Data'},
        ),
    ]
