# Generated by Django 5.1.2 on 2025-02-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabsl_internal_option_id', models.IntegerField(blank=True, null=True)),
                ('option_name', models.CharField(blank=True, max_length=40, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options', to='common.log')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorOptionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabsl_internal_state_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('target', models.BooleanField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options_states', to='common.log')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_options_states', to='behavior.behavioroption')),
            ],
        ),
        migrations.CreateModel(
            name='XabslSymbolComplete',
            fields=[
                ('log_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='xabsl_symbol_complete', serialize=False, to='common.log')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'XabslSymbolComplete',
                'indexes': [models.Index(fields=['log_id'], name='behavior_xa_log_id__c4573f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorFrameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='common.log')),
                ('options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='behavior.behavioroption')),
                ('active_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_frame_option', to='behavior.behavioroptionstate')),
            ],
            options={
                'indexes': [models.Index(fields=['log_id', 'frame', 'options_id'], name='behavior_be_log_id__f0e391_idx')],
                'unique_together': {('log_id', 'options_id', 'frame', 'active_state')},
            },
        ),
        migrations.CreateModel(
            name='XabslSymbolSparse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabsl_symbol_sparse', to='common.log')),
            ],
            options={
                'verbose_name_plural': 'XabslSymbolSparse',
                'indexes': [models.Index(fields=['log_id', 'frame'], name='behavior_xa_log_id__be49e0_idx')],
                'unique_together': {('log_id', 'frame')},
            },
        ),
    ]
